test:
  runs-on: windows-latest # Using GitHub's Windows runner for testing
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test | Tee-Object -FilePath test-results.txt

    - name: Ensure Artifact Directory Exists
      run: mkdir -p test-results

    - name: Move Test Results to Directory
      run: mv test-results.txt test-results/

    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results/
