name: CI/CD Pipeline for Node.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted # Using your self-hosted Windows runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Create Test Results Directory
        run: mkdir test-results

      - name: Run Tests and Save Results
        run: npm test | Tee-Object -FilePath test-results/test-results.txt

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results/

  deploy:
    runs-on: self-hosted
    needs: test # Ensures deployment runs only after testing

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: test-results/

      - name: Display Test Results
        run: type test-results/test-results.txt

      - name: Install Dependencies
        run: npm install

      - name: Start Application
        run: node server.js
